# Documentation: http://docs.travis-ci.com/user/languages/julia
language: julia
notifications:
  email: false
julia:
  - 1.3
  - 1.5
  - 1.6
  - nightly
os:
  - linux
  - osx
  - windows
arch:
  - x64
cache:
  directories:
    - ~/.julia/artifacts
jobs:
  fast_finish: true
  allow_failures:
    - julia: nightly

matrix:
  allow_failures:
    - julia: nightly
  exclude:
    - os: osx
      julia: 1.6
    - os: windows
      julia: 1.6
    - os: osx
      julia: nightly
    - os: windows
      julia: nightly
  fast_finish: true
branches:
  only:
    - master
    - /release-.*/
